name: nhctl

on:
  push:
    branches: [ main ]
    paths:
    - 'cmd/nhctl/**'
    - 'internal/nhctl/**'
    - 'pkg/nhctl/**'
    - '!*/**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-nhctl:
    name: Build nhctl
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    
