name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-nhctl:
    name: Release nhctl
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build nhctl
      env:
        VERSION: ${{ env.RELEASE_VERSION }}
      run: |
        make nhctl-windows

    - name: Create nhctl Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: print release
      run: |
        echo ${{ steps.create_release.outputs.upload_url }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/nhctl-windows-amd64.exe
        asset_name: nhctl-windows-amd64.exe
        asset_content_type: application/octet-stream

  release-windows:
    needs: release-nhctl
    name: windows
    runs-on: windows-latest
    steps:
    - name: hello
      run: |
        dir
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: package
      run: |
        choco install curl
        choco install unzip
        curl -L https://github.com/nocalhost/nocalhost/releases/download/latest/nhctl-windows-amd64.exe build/nhctl.exe
        curl -L https://storage.googleapis.com/kubernetes-release/release/v2.20.0/bin/windows/amd64/kubectl.exe -o build/kubectl.exe
        curl -L https://get.helm.sh/helm-v3.4.2-windows-amd64.zip -o build/helm.zip
        unzip build/helm.zip
        dir build
        issc -/DAppVersion=${{ env.RELEASE_VERSION }} scripts/release/nocalhost.iss
        dir build

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/NocalhostInstaller.exe
        asset_name: NocalhostInstaller.exe
        asset_content_type: application/octet-stream

